### ISSUE TITLE
Unable to Build Using Gradle.. Help

### ISSUE THREAD

**Issue by kathrynchou** [nebula-plugins/gradle-netflixoss-project-plugin#51]
[kchou@den02tez ndbench]$ gradle --stacktrace | more

FAILURE: Build failed with an exception.

* Where:
Build file '/scratch/kchou/netflix/real_netflix/ndbench/build.gradle' line: 14

* What went wrong:
Plugin [id: 'de.undercouch.download', version: '3.4.2'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'de.undercouch.download:de.undercouch.download.gradle\
.plugin:3.4.2')
  Searched in the following repositories:
    Gradle Central Plugin Repository

**Comment by rpalcolea** [comment]
Hi @kathrynchou , I cloned https://github.com/Netflix/ndbench  and run same command without issues

```
ndbench git/master
❯ ./gradlew --stacktrace --refresh-dependencies | more
Inferred project: ndbench, version: 0.5.0-SNAPSHOT
Publication nebula not found in project :.

Welcome to Gradle 4.8.1.

To run a build, run gradlew <task> ...

To see a list of available tasks, run gradlew tasks

To see a list of command-line options, run gradlew --help

To see more detail about a task, run gradlew help --task <task>

For troubleshooting, visit https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.8.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 9s
1 actionable task: 1 executed
```

Also tried to build the environment:

```
❯

ndbench git/master  8s
❯ ./gradlew bE

> Configure project :
Inferred project: ndbench, version: 0.5.0-SNAPSHOT
Publication nebula not found in project :.

> Task :buildEnvironment

------------------------------------------------------------
Root project - ndbench
------------------------------------------------------------

classpath
+--- com.netflix.nebula:gradle-extra-configurations-plugin:latest.release -> 5.0.0
|    \--- com.netflix.nebula:nebula-gradle-interop:1.0.2
|         \--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.2.70
|              \--- org.jetbrains.kotlin:kotlin-stdlib:1.2.70
|                   +--- org.jetbrains.kotlin:kotlin-stdlib-common:1.2.70
|                   \--- org.jetbrains:annotations:13.0
+--- org.akhikhl.gretty:gretty:2.0.0
|    +--- org.akhikhl.gretty:gretty-core:2.0.0
|    |    +--- org.codehaus.groovy:groovy:2.4.11
|    |    +--- org.codehaus.groovy:groovy-json:2.4.11
|    |    |    \--- org.codehaus.groovy:groovy:2.4.11
|    |    +--- commons-cli:commons-cli:1.2
|    |    +--- commons-configuration:commons-configuration:1.10
|    |    |    +--- commons-lang:commons-lang:2.6
|    |    |    \--- commons-logging:commons-logging:1.1.1 -> 1.2
|    |    +--- commons-io:commons-io:2.4
|    |    +--- org.apache.commons:commons-lang3:3.3.2 -> 3.4
|    |    +--- org.apache.servicemix.bundles:org.apache.servicemix.bundles.bcprov-jdk16:1.46_3
|    |    \--- org.springframework.boot:spring-boot-devtools:1.3.3.RELEASE
|    |         +--- org.springframework.boot:spring-boot:1.3.3.RELEASE
|    |         |    +--- org.springframework:spring-core:4.2.5.RELEASE -> 4.3.9.RELEASE
|    |         |    |    \--- commons-logging:commons-logging:1.2
|    |         |    \--- org.springframework:spring-context:4.2.5.RELEASE
|    |         |         +--- org.springframework:spring-aop:4.2.5.RELEASE
|    |         |         |    +--- aopalliance:aopalliance:1.0
|    |         |         |    +--- org.springframework:spring-beans:4.2.5.RELEASE
|    |         |         |    |    \--- org.springframework:spring-core:4.2.5.RELEASE -> 4.3.9.RELEASE (*)
|    |         |         |    \--- org.springframework:spring-core:4.2.5.RELEASE -> 4.3.9.RELEASE (*)
|    |         |         +--- org.springframework:spring-beans:4.2.5.RELEASE (*)
|    |         |         +--- org.springframework:spring-core:4.2.5.RELEASE -> 4.3.9.RELEASE (*)
|    |         |         \--- org.springframework:spring-expression:4.2.5.RELEASE
|    |         |              \--- org.springframework:spring-core:4.2.5.RELEASE -> 4.3.9.RELEASE (*)
|    |         \--- org.springframework.boot:spring-boot-autoconfigure:1.3.3.RELEASE
|    |              \--- org.springframework.boot:spring-boot:1.3.3.RELEASE (*)
|    +--- org.springframework.boot:spring-boot-loader-tools:1.5.4.RELEASE
|    |    \--- org.springframework:spring-core:4.3.9.RELEASE (*)
|    \--- org.eclipse.jetty:jetty-util:8.1.8.v20121106
+--- nebula.netflixoss:nebula.netflixoss.gradle.plugin:5.1.1
|    \--- com.netflix.nebula:gradle-netflixoss-project-plugin:5.1.1
|         +--- com.netflix.nebula:gradle-contacts-plugin:3.0.1
|         +--- com.netflix.nebula:gradle-dependency-lock-plugin:5.0.6
|         |    +--- com.netflix.nebula:nebula-gradle-interop:0.5.0 -> 1.0.2 (*)
|         |    +--- com.netflix.nebula:gradle-scm-plugin:3.0.1
|         |    +--- com.netflix.nebula:nebula-dependency-base-plugin:0.4.0
|         |    |    \--- org.jetbrains.kotlin:kotlin-stdlib-jre7:1.2.10
|         |    |         \--- org.jetbrains.kotlin:kotlin-stdlib:1.2.10 -> 1.2.70 (*)
|         |    +--- org.codehaus.groovy.modules.http-builder:http-builder:0.7.1 -> 0.7.2
|         |    |    +--- org.apache.httpcomponents:httpclient:4.2.1 -> 4.5.3
|         |    |    |    +--- org.apache.httpcomponents:httpcore:4.4.6
|         |    |    |    +--- commons-logging:commons-logging:1.2
|         |    |    |    \--- commons-codec:commons-codec:1.9
|         |    |    +--- net.sf.json-lib:json-lib:2.3
|         |    |    |    +--- commons-beanutils:commons-beanutils:1.8.0
|         |    |    |    |    \--- commons-logging:commons-logging:1.1.1 -> 1.2
|         |    |    |    +--- commons-collections:commons-collections:3.2.1
|         |    |    |    +--- commons-lang:commons-lang:2.4 -> 2.6
|         |    |    |    +--- commons-logging:commons-logging:1.1.1 -> 1.2
|         |    |    |    \--- net.sf.ezmorph:ezmorph:1.0.6
|         |    |    |         \--- commons-lang:commons-lang:2.3 -> 2.6
|         |    |    +--- net.sourceforge.nekohtml:nekohtml:1.9.16
|         |    |    |    \--- xerces:xercesImpl:2.9.1
|         |    |    \--- xml-resolver:xml-resolver:1.2
|         |    \--- org.jetbrains.kotlin:kotlin-stdlib-jre7:1.2.10 (*)
|         +--- com.netflix.nebula:gradle-info-plugin:3.7.1
|         |    +--- com.perforce:p4java:2015.2.1365273
|         |    |    \--- com.jcraft:jzlib:1.1.2
|         |    +--- com.netflix.nebula:gradle-contacts-plugin:3.0.1
|         |    +--- org.eclipse.jgit:org.eclipse.jgit:4.4.1.201607150455-r -> 4.5.2.201704071617-r
|         |    |    +--- com.jcraft:jsch:0.1.53 -> 0.1.54
|         |    |    +--- com.googlecode.javaewah:JavaEWAH:0.7.9
|         |    |    +--- org.apache.httpcomponents:httpclient:4.3.6 -> 4.5.3 (*)
|         |    |    \--- org.slf4j:slf4j-api:1.7.2 -> 1.7.25
|         |    \--- org.tmatesoft.svnkit:svnkit:1.8.12
|         |         +--- com.jcraft:jsch.agentproxy.svnkit-trilead-ssh2:0.0.7
|         |         |    +--- com.trilead:trilead-ssh2:1.0.0-build217 -> 1.0.0-build220
|         |         |    \--- com.jcraft:jsch.agentproxy.core:0.0.7 -> 0.0.9
|         |         +--- com.trilead:trilead-ssh2:1.0.0-build220
|         |         +--- net.java.dev.jna:jna-platform:4.1.0
|         |         |    \--- net.java.dev.jna:jna:4.1.0
|         |         +--- net.java.dev.jna:jna:4.1.0
|         |         +--- com.jcraft:jsch.agentproxy.connector-factory:0.0.7
|         |         |    +--- com.jcraft:jsch.agentproxy.core:0.0.7 -> 0.0.9
|         |         |    +--- com.jcraft:jsch.agentproxy.usocket-jna:0.0.7 -> 0.0.9
|         |         |    |    +--- com.jcraft:jsch.agentproxy.core:0.0.9
|         |         |    |    +--- net.java.dev.jna:jna:4.1.0
|         |         |    |    \--- net.java.dev.jna:jna-platform:4.1.0 (*)
|         |         |    +--- com.jcraft:jsch.agentproxy.usocket-nc:0.0.7 -> 0.0.9
|         |         |    |    \--- com.jcraft:jsch.agentproxy.core:0.0.9
|         |         |    +--- com.jcraft:jsch.agentproxy.sshagent:0.0.7 -> 0.0.9
|         |         |    |    \--- com.jcraft:jsch.agentproxy.core:0.0.9
|         |         |    \--- com.jcraft:jsch.agentproxy.pageant:0.0.7 -> 0.0.9
|         |         |         +--- com.jcraft:jsch.agentproxy.core:0.0.9
|         |         |         +--- net.java.dev.jna:jna:4.1.0
|         |         |         \--- net.java.dev.jna:jna-platform:4.1.0 (*)
|         |         +--- de.regnis.q.sequence:sequence-library:1.0.3
|         |         \--- org.tmatesoft.sqljet:sqljet:1.1.10
|         |              \--- org.antlr:antlr-runtime:3.4
|         +--- com.netflix.nebula:nebula-bintray-plugin:3.5.5
|         |    +--- com.jfrog.bintray.gradle:gradle-bintray-plugin:1.8.4
|         |    |    +--- org.codehaus.groovy.modules.http-builder:http-builder:0.7.2 (*)
|         |    |    \--- org.apache.maven:maven-ant-tasks:2.1.3
|         |    |         +--- org.apache.ant:ant:1.8.0
|         |    |         |    \--- org.apache.ant:ant-launcher:1.8.0
|         |    |         +--- classworlds:classworlds:1.1-alpha-2
|         |    |         +--- org.codehaus.plexus:plexus-container-default:1.0-alpha-9-stable-1
|         |    |         |    +--- junit:junit:3.8.1
|         |    |         |    +--- org.codehaus.plexus:plexus-utils:1.0.4 -> 2.0.5
|         |    |         |    \--- classworlds:classworlds:1.1-alpha-2
|         |    |         +--- org.codehaus.plexus:plexus-utils:1.5.15 -> 2.0.5
|         |    |         +--- org.codehaus.plexus:plexus-interpolation:1.11
|         |    |         +--- org.apache.maven:maven-artifact:2.2.1
|         |    |         |    \--- org.codehaus.plexus:plexus-utils:1.5.15 -> 2.0.5
|         |    |         +--- org.apache.maven:maven-artifact-manager:2.2.1
|         |    |         |    +--- org.apache.maven:maven-repository-metadata:2.2.1
|         |    |         |    |    \--- org.codehaus.plexus:plexus-utils:1.5.15 -> 2.0.5
|         |    |         |    +--- org.codehaus.plexus:plexus-utils:1.5.15 -> 2.0.5
|         |    |         |    +--- org.apache.maven:maven-artifact:2.2.1 (*)
|         |    |         |    +--- org.codehaus.plexus:plexus-container-default:1.0-alpha-9-stable-1 (*)
|         |    |         |    +--- org.apache.maven.wagon:wagon-provider-api:1.0-beta-6
|         |    |         |    |    \--- org.codehaus.plexus:plexus-utils:1.4.2 -> 2.0.5
|         |    |         |    \--- backport-util-concurrent:backport-util-concurrent:3.1
|         |    |         +--- org.apache.maven:maven-model:2.2.1
|         |    |         |    \--- org.codehaus.plexus:plexus-utils:1.5.15 -> 2.0.5
|         |    |         +--- org.apache.maven:maven-project:2.2.1
|         |    |         |    +--- org.apache.maven:maven-settings:2.2.1
|         |    |         |    |    +--- org.apache.maven:maven-model:2.2.1 (*)
|         |    |         |    |    +--- org.codehaus.plexus:plexus-interpolation:1.11
|         |    |         |    |    +--- org.codehaus.plexus:plexus-utils:1.5.15 -> 2.0.5
|         |    |         |    |    \--- org.codehaus.plexus:plexus-container-default:1.0-alpha-9-stable-1 (*)
|         |    |         |    +--- org.apache.maven:maven-profile:2.2.1
|         |    |         |    |    +--- org.apache.maven:maven-model:2.2.1 (*)
|         |    |         |    |    +--- org.codehaus.plexus:plexus-utils:1.5.15 -> 2.0.5
|         |    |         |    |    +--- org.codehaus.plexus:plexus-interpolation:1.11
|         |    |         |    |    \--- org.codehaus.plexus:plexus-container-default:1.0-alpha-9-stable-1 (*)
|         |    |         |    +--- org.apache.maven:maven-model:2.2.1 (*)
|         |    |         |    +--- org.apache.maven:maven-artifact-manager:2.2.1 (*)
|         |    |         |    +--- org.apache.maven:maven-plugin-registry:2.2.1
|         |    |         |    |    +--- org.codehaus.plexus:plexus-utils:1.5.15 -> 2.0.5
|         |    |         |    |    \--- org.codehaus.plexus:plexus-container-default:1.0-alpha-9-stable-1 (*)
|         |    |         |    +--- org.codehaus.plexus:plexus-interpolation:1.11
|         |    |         |    +--- org.codehaus.plexus:plexus-utils:1.5.15 -> 2.0.5
|         |    |         |    +--- org.apache.maven:maven-artifact:2.2.1 (*)
|         |    |         |    \--- org.codehaus.plexus:plexus-container-default:1.0-alpha-9-stable-1 (*)
|         |    |         +--- org.apache.maven:maven-error-diagnostics:2.2.1
|         |    |         |    \--- org.codehaus.plexus:plexus-container-default:1.0-alpha-9-stable-1 (*)
|         |    |         +--- org.apache.maven:maven-settings:2.2.1 (*)
|         |    |         +--- org.apache.maven.wagon:wagon-file:1.0-beta-6
|         |    |         |    \--- org.apache.maven.wagon:wagon-provider-api:1.0-beta-6 (*)
|         |    |         +--- org.apache.maven.wagon:wagon-http-lightweight:1.0-beta-6
|         |    |         |    +--- org.apache.maven.wagon:wagon-http-shared:1.0-beta-6
|         |    |         |    |    +--- nekohtml:xercesMinimal:1.9.6.2
|         |    |         |    |    +--- nekohtml:nekohtml:1.9.6.2
|         |    |         |    |    \--- org.apache.maven.wagon:wagon-provider-api:1.0-beta-6 (*)
|         |    |         |    \--- org.apache.maven.wagon:wagon-provider-api:1.0-beta-6 (*)
|         |    |         \--- org.apache.maven.wagon:wagon-provider-api:1.0-beta-6 (*)
|         |    \--- org.jfrog.buildinfo:build-info-extractor-gradle:4.7.5
|         |         +--- commons-lang:commons-lang:2.4 -> 2.6
|         |         +--- commons-logging:commons-logging:1.1.1 -> 1.2
|         |         +--- commons-io:commons-io:2.2 -> 2.4
|         |         +--- org.jfrog.buildinfo:build-info-extractor:2.11.3
|         |         |    +--- commons-lang:commons-lang:2.4 -> 2.6
|         |         |    +--- commons-logging:commons-logging:1.1.1 -> 1.2
|         |         |    +--- commons-io:commons-io:2.2 -> 2.4
|         |         |    +--- com.google.guava:guava:18.0
|         |         |    +--- com.thoughtworks.xstream:xstream:1.4.10
|         |         |    |    +--- xmlpull:xmlpull:1.1.3.1
|         |         |    |    \--- xpp3:xpp3_min:1.1.4c
|         |         |    \--- org.jfrog.buildinfo:build-info-client:2.11.3
|         |         |         +--- commons-lang:commons-lang:2.4 -> 2.6
|         |         |         +--- commons-logging:commons-logging:1.1.1 -> 1.2
|         |         |         +--- commons-io:commons-io:2.2 -> 2.4
|         |         |         +--- com.google.guava:guava:18.0
|         |         |         +--- com.thoughtworks.xstream:xstream:1.4.10 (*)
|         |         |         +--- org.jfrog.buildinfo:build-info-api:2.11.3
|         |         |         |    +--- commons-lang:commons-lang:2.4 -> 2.6
|         |         |         |    +--- commons-logging:commons-logging:1.1.1 -> 1.2
|         |         |         |    +--- commons-io:commons-io:2.2 -> 2.4
|         |         |         |    +--- com.google.guava:guava:18.0
|         |         |         |    +--- com.thoughtworks.xstream:xstream:1.4.10 (*)
|         |         |         |    +--- com.fasterxml.jackson.core:jackson-databind:2.9.5
|         |         |         |    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.9.0
|         |         |         |    |    \--- com.fasterxml.jackson.core:jackson-core:2.9.5
|         |         |         |    +--- com.fasterxml.jackson.core:jackson-core:2.9.5
|         |         |         |    \--- org.apache.commons:commons-compress:1.16
|         |         |         |         \--- org.objenesis:objenesis:2.6
|         |         |         +--- org.apache.httpcomponents:httpclient:4.5.2 -> 4.5.3 (*)
|         |         |         +--- org.apache.httpcomponents:httpcore:4.4.5 -> 4.4.6
|         |         |         +--- com.fasterxml.jackson.core:jackson-core:2.9.5
|         |         |         \--- commons-codec:commons-codec:1.8 -> 1.9
|         |         \--- org.apache.ivy:ivy:2.2.0
|         +--- com.netflix.nebula:nebula-core:4.0.1
|         |    +--- org.apache.commons:commons-lang3:3.4
|         |    \--- org.apache.httpcomponents:httpclient-cache:4.5.2
|         |         +--- org.apache.httpcomponents:httpclient:4.5.2 -> 4.5.3 (*)
|         |         \--- commons-logging:commons-logging:1.2
|         +--- com.netflix.nebula:nebula-project-plugin:4.0.1
|         |    +--- com.netflix.nebula:nebula-gradle-interop:0.5.0 -> 1.0.2 (*)
|         |    +--- com.netflix.nebula:nebula-core:4.0.1 (*)
|         |    +--- com.netflix.nebula:nebula-publishing-plugin:5.1.5 -> 7.2.3
|         |    +--- com.netflix.nebula:gradle-contacts-plugin:3.0.1
|         |    +--- com.netflix.nebula:gradle-dependency-lock-plugin:5.0.0 -> 5.0.6 (*)
|         |    \--- com.netflix.nebula:gradle-info-plugin:3.6.0 -> 3.7.1 (*)
|         +--- com.netflix.nebula:nebula-publishing-plugin:7.2.3
|         +--- com.netflix.nebula:nebula-release-plugin:6.3.5
|         |    \--- org.ajoberstar:gradle-git:1.7.2
|         |         +--- org.ajoberstar:grgit:1.9.3
|         |         |    +--- org.eclipse.jgit:org.eclipse.jgit:4.5.2.201704071617-r (*)
|         |         |    +--- org.eclipse.jgit:org.eclipse.jgit.ui:4.5.2.201704071617-r
|         |         |    |    \--- org.eclipse.jgit:org.eclipse.jgit:4.5.2.201704071617-r (*)
|         |         |    +--- com.jcraft:jsch.agentproxy.jsch:0.0.9
|         |         |    |    +--- com.jcraft:jsch:0.1.49 -> 0.1.54
|         |         |    |    \--- com.jcraft:jsch.agentproxy.core:0.0.9
|         |         |    +--- com.jcraft:jsch.agentproxy.pageant:0.0.9 (*)
|         |         |    +--- com.jcraft:jsch.agentproxy.sshagent:0.0.9 (*)
|         |         |    +--- com.jcraft:jsch.agentproxy.usocket-jna:0.0.9 (*)
|         |         |    +--- com.jcraft:jsch.agentproxy.usocket-nc:0.0.9 (*)
|         |         |    +--- com.jcraft:jsch:0.1.54
|         |         |    \--- org.slf4j:slf4j-api:1.7.25
|         |         \--- com.github.zafarkhaja:java-semver:0.9.0
|         +--- com.netflix.nebula:gradle-java-cross-compile-plugin:1.0.0
|         |    +--- com.netflix.nebula:nebula-gradle-interop:0.5.0 -> 1.0.2 (*)
|         |    \--- org.jetbrains.kotlin:kotlin-stdlib-jre7:1.2.0 -> 1.2.10 (*)
|         \--- gradle.plugin.nl.javadude.gradle.plugins:license-gradle-plugin:0.13.1
|              +--- org.codehaus.plexus:plexus-utils:2.0.5
|              +--- com.mycila.xmltool:xmltool:3.3
|              \--- com.mycila.maven-license-plugin:maven-license-plugin:1.10.b1
|                   +--- com.mycila.xmltool:xmltool:3.3
|                   \--- org.codehaus.plexus:plexus-utils:2.0.5
\--- de.undercouch.download:de.undercouch.download.gradle.plugin:3.4.2
     \--- de.undercouch:gradle-download-task:3.4.2
          \--- org.apache.httpcomponents:httpclient:4.5.3 (*)

(*) - dependencies omitted (listed previously)

A web-based, searchable dependency report is available by adding the --scan option.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.8.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed

ndbench git/master
❯
```

any chance you had a network issue and that's why the plugin was not found?

**Comment by rpalcolea** [comment]
Also, I believe that wouldn't be a netflixoss-project-plugin issue because de.undercouch.download is part of ndbench build.gradle and not something we add to this plugin

**Comment by rpalcolea** [comment]
I'd suggest also trying with the wrapper which comes with the project:

`./gradlew --stacktrace | more`

I'm closing this issue in favor of https://github.com/Netflix/ndbench/issues/224

**Comment by kathrynchou** [comment]
How to workaround this issue? I had proxy set.. 
What is de.undercouch.download plugin?? 


-Kathryn 



home/kchou/netflix/real_netflix/ndbench 
[kchou@den02tez ndbench]$ ./gradlew --stacktrace --refresh-dependencies | more 
Downloading https://services.gradle.org/distributions/gradle-4.8.1-bin.zip 

Exception in thread "main" java.net.ConnectException: Connection timed out (Connection timed out) 
at java.net.PlainSocketImpl.socketConnect(Native Method) 
at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) 
at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) 
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) 
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) 
at java.net.Socket.connect(Socket.java:589) 
at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673) 
at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173) 
at sun.net.NetworkClient.doConnect(NetworkClient.java:180) 
at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) 
at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) 
at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264) 
at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367) 
at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:200) 
at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1157) 
at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032) 
at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) 
at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546) 
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474) 
at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254) 
at org.gradle.wrapper.Download.downloadInternal(Download.java:66) 
at org.gradle.wrapper.Download.download(Download.java:51) 
at org.gradle.wrapper.Install$1.call(Install.java:62) 
at org.gradle.wrapper.Install$1.call(Install.java:48) 
at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69) 
at org.gradle.wrapper.Install.createDist(Install.java:48) 
at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107) 
at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61) 
----- notifications@github.com wrote: 
> 

I'd suggest also trying with the wrapper which comes with the project: 

./gradlew --stacktrace | more 

I'm closing this issue in favor of Netflix/ndbench#224

**Comment by kathrynchou** [comment]
How to workaround this issue? I had proxy set.. 
What is de.undercouch.download plugin?? 

-Kathryn 

----- notifications@github.com wrote: 
> 

Also, I believe that wouldn't be a netflixoss-project-plugin issue because de.undercouch.download is part of ndbench build.gradle and not something we add to this plugin

**Comment by rpalcolea** [comment]
@kathrynchou 
The download plugin is https://github.com/michel-kraemer/gradle-download-task 

You can take a look on https://docs.gradle.org/current/userguide/build_environment.html#sec:accessing_the_web_via_a_proxy
